services:
  php:
    build: ./docker/php
    container_name: '${APP_NAME}_php'
    restart: unless-stopped
    tty: true
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - docker.network
    volumes:
      - .:/var/www/inachis

  gulp:
    build:
      context: .
      dockerfile: ./docker/gulp/Dockerfile
    command: [ 'gulp' ]
    container_name: '${APP_NAME}_gulp'
    depends_on:
      - php
    networks:
      - docker.network
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www/inachis
      - node_modules:/var/www/inachis/node_modules

  apache:
    build: ./docker/apache
    command: ["httpd-foreground"]
    container_name: '${APP_NAME}_apache'
    restart: unless-stopped
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker.network
    volumes:
      - .:/var/www/inachis

# changes to the below require db to be rebuilt (remove data directory contents)
  mariadb:
    image: mariadb:latest
    container_name: '${APP_NAME}_db'
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MYSQL_DATABASE:-inachis}
      MARIADB_USER: ${MYSQL_USER:-inachis}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:-Secret123}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "33016:3306"
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 30s
      retries: 3
      timeout: 30s
    networks:
      - docker.network

volumes:
  node_modules:
  mysqldata: {}

networks:
  docker.network:
    driver: bridge
